apiVersion: apps/v1
kind: Deployment
metadata:
  name: novabank-app
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: novabank-app
  template:
    metadata:
      labels:
        app: novabank-app
    spec:
      containers:
      - name: novabank-app
        image: nginx:1.21
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"